ALTER TABLE "Entry" ADD COLUMN "foodName" TEXT;
ALTER TABLE "Entry" ADD COLUMN "portionGrams" DOUBLE PRECISION;
ALTER TABLE "Entry" ADD COLUMN "proteinGrams" DOUBLE PRECISION;
ALTER TABLE "Entry" ADD COLUMN "carbsGrams" DOUBLE PRECISION;
ALTER TABLE "Entry" ADD COLUMN "fatGrams" DOUBLE PRECISION;
ALTER TABLE "Entry" ADD COLUMN "foodSource" TEXT;
